project/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import *

app_name = 'app'

urlpatterns = [
                  path('accounts/login/', BBLoginView.as_view(), name='login'),
                  path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
                  path('accounts/profile/<int:pk>/change/', ChangeUserInfoView.as_view(), name='profile_change'),
                  path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
                  path('accounts/profile/', profile, name='profile'),
                  path('accounts/signup/', SignUpView.as_view(), name='signup'),
                  path('accounts/delete/', DeleteUserView.as_view(), name='user_delete'),
                  path('', Index.as_view(), name='index'),
                  path('<int:pk>/', DetailPoll.as_view(), name='detail'),
                  path('<int:poll_id>/vote/', views.vote, name='vote'),
                  path('<int:pk>/results/', ResultsView.as_view(), name='results')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

project/app/templates/layout/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <title>{% block title %} Главная {% endblock %} - Опросник </title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app:index' %}">Опросник</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Профиль
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'app:profile' %}">Мой профиль</a>
                        <a class="dropdown-item" href="{% url 'app:profile_change' user.id %}">Изменить личные данные</a>
                        <a class="dropdown-item" href="{% url 'app:password_change' %}">Изменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'app:logout' %}">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'app:user_delete' %}">Удалить</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:signup' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:login' %}">Вход</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>