project/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import *

app_name = 'app'

urlpatterns = [
                  path('accounts/login/', BBLoginView.as_view(), name='login'),
                  path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
                  path('accounts/profile/<int:pk>/change/', ChangeUserInfoView.as_view(), name='profile_change'),
                  path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
                  path('accounts/profile/', profile, name='profile'),
                  path('accounts/signup/', SignUpView.as_view(), name='signup'),
                  path('accounts/delete/', DeleteUserView.as_view(), name='user_delete'),
                  path('', Index.as_view(), name='index'),
                  path('<int:pk>/', DetailPoll.as_view(), name='detail'),
                  path('<int:poll_id>/vote/', views.vote, name='vote'),
                  path('<int:pk>/results/', ResultsView.as_view(), name='results')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

project/app/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Оповещать при новых комментариях?')
    avatar = models.ImageField(upload_to='media', blank=False, null=False)

    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        return self.username


class Poll(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    full_description = models.TextField()
    publish_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField()
    photo = models.ImageField(upload_to='media')

    def __str__(self):
        return self.title


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=180)
    votes = models.IntegerField()

    def __str__(self):
        return self.choice_text


class Voter(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

project/app/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %} Правка личных данных {% endblock %}

{% block content %}
   <h2>Правка личных данных пользователя {{ user.username }}</h2>
   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{form.as_p}}
       {% if user.avatar %}
       <img src="{{ user.avatar.url }}" alt="Аватар отсутствует" width="200px">
       {% endif %}
       <input type="submit" value="Изменить">
   </form>
{% endblock %}

project/app/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %} Удаление пользователя {% endblock %}

{% block content %}
   <h2>Удаление пользователя {{ user.username }}</h2>
   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
        <input type="submit" value="Удалить">
   </form>
{% endblock %}

project/app/templates/main/detail.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block content %}

<form action="{% url 'app:vote' polls.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ polls.title }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in polls.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <img src="{{ polls.photo.url }}" alt="Изображение отсутствует!" width="350px">
    </fieldset>
    <input type="submit" value="Проголосовать">
</form>

{% endblock %}

project/app/templates/main/index.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block content %}

{% for message in messages %}
<div class="text-red alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}

{% for poll in polls %}
<h2>{{ poll.title }}</h2>
<p>{{ poll.short_description }}</p>
<p>{{ poll.publish_date }}</p>

<ul>
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

<a href="{% url 'app:results' poll.id %}">View Results</a>
<a href="{% url 'app:detail' poll.id %}">Vote Now</a>

{% endfor %}

{% endblock %}

project/app/templates/main/login.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %} Вход {% endblock %}

{% block content %}
   <h2>Вход</h2>
   {% if user.is_authenticated %}
       <p>Вы уже выполнили вход.</p>
   {% else %}
       <form method="POST" enctype="multipart/form-data">
           {% csrf_token %}
           {{form.as_p}}
            <button type="submit">Войти</button>
       </form>
   {% endif %}
{% endblock %}

project/app/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %} Выход {% endblock %}

{% block content %}
   <h2>Выход</h2>
   <p>Вы успешно вышли с сайта.</p>
{% endblock %}

project/app/templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% block title %} Изменение пароля {% endblock %}

{% block content %}

<h2>Изменение пароля</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
</form>

{% endblock %}

project/app/templates/main/profile.html
{% extends "layout/basic.html" %}


{% block title %} Профиль пользователя {% endblock %}

{% block content %}
   <h2>Профиль пользователя {{ user.username }}</h2>
   {% if user.first_name and user.last_name %}
       <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p> <br>
   {% else %}
       <p>Здравствуйте! </p>
   {% endif %}
    {% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="Аватар отсутствует" width="200px">
    {% endif %}
   <h3>Ваши объявления</h3>
{% endblock %}

project/app/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %} Регистрация завершена {% endblock %}

{% block content %}
   <h2>Регистрация</h2>
   <p>Регистрация пользователя завершена</p>
{% endblock %}

project/app/templates/main/results.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block content %}

<h1>{{ poll.title }}</h1>

<ul>
    {% for choice, percentage in choices_with_percentages %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}} ({{percentage}}%)</li>
    {% endfor %}
</ul>
<a href="{% url 'app:index' %}">На главную</a>

{% endblock %}

project/app/templates/main/signup.html
{% extends 'layout/basic.html' %}

{% load static %}

{% load static %}

{% block content %}
   <h2>Регистрация</h2>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {{form.as_p}}
            <input type="submit" value="Войти">
       </form>
{% endblock %}